version: '3.9'

services:
  web:
    build: .
    restart: always
    ports:
      - "3003:3000"
    env_file:
      - .env
    container_name: web
    image: 8881981/web:1
    networks:
      - net

networks:
  net:

