import Header from '@/components/MainLayout/Header/Header';
import Sidebar from '@/components/MainLayout/Sidebar/Sidebar';
import '@/styles/globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div className='wrapperMainLayout'>
          <Header className='header'/>
          <Sidebar className='sidebar'/>
          <div className='content'>{children}</div>
        </div>
      </body>
    </html>
  );
}
